# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/wush978/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

# Adapt as necessary starting from here

build_script:
  - Rscript -e "download.file('https://raw.githubusercontent.com/wush978/R/gh-pages/.test_course.R', destfile = '.test_course.R')"
  - Rscript -e "options(repos = c(CRAN='https://cloud.r-project.org'));source('https://wush978.github.io/R/init-swirl.R')"

test_script:
  - Rscript .test_course.R push

on_failure:
  - travis-tool.sh dump_logs

environment:
  R_VERSION: release
